name: Integration Tests Workflow

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    strategy:
      matrix:
        pythonversion: ["3.7","3.8","3.9","3.10"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.pythonversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pythonversion }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Build C code
      run: |
        make install
      working-directory: c-source
    - name: Integration tests
      run: |
        pipenv run python -m unittest integration_tests.native
