name: C-code Lint+Build+Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    strategy:
      matrix:
        compilerversion: [9,10,11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ matrix.compilerversion }}
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: gcc-${{ matrix.compilerversion }}
  build-clang:
    strategy:
      matrix:
        compilerversion: [10,11,12,13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.compilerversion }}
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: clang-${{ matrix.compilerversion }}
