name: C-code Lint+Build+Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 10
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: gcc-10
  build-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-clang@v1
      with:
        version: 12
        platform: x64
    - name: build
      run: |
        make install
      env:
        CC: clang-12
