# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint+Test

defaults:
  run:
    working-directory: python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  black:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install .
    - name: Syntax Check with Black
      run: |
        black --check asciiserialcom tests

  ## Not trying to fix right now
  #mypy:

  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up Python 3.9
  #    uses: actions/setup-python@v2
  #    with:
  #      python-version: 3.9
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install mypy
  #      pip install .
  #  - name: Static Analysis with mypy
  #    run: |
  #      mypy asciiserialcom

  unittest:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install .
    - name: Python unittest
      run: |
        coverage run --source=asciiserialcom -m unittest tests
    - name: Python coverage report
      run: |
        coverage report
